apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: banking-db
  namespace: banking-data
spec:
  instances: 3

  imageName: ghcr.io/cloudnative-pg/postgresql:16.6

  postgresql:
    parameters:
      max_connections: "100"
      shared_buffers: "256MB"
      effective_cache_size: "512MB"
      wal_level: "replica"
      max_wal_senders: "10"

  bootstrap:
    initdb:
      database: banking
      owner: banking_app

  storage:
    size: 20Gi
    storageClass: local-path

  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      memory: 1Gi

  affinity:
    enablePodAntiAffinity: true
    topologyKey: kubernetes.io/hostname
    podAntiAffinityType: required

  monitoring:
    enablePodMonitor: false
