apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: dual-role
  namespace: banking-messaging
  labels:
    strimzi.io/cluster: banking-kafka
spec:
  replicas: 3
  roles:
    - controller
    - broker
  storage:
    type: jbod
    volumes:
      - id: 0
        type: persistent-claim
        size: 20Gi
        deleteClaim: false
        kraftMetadata: shared
  template:
    pod:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  strimzi.io/cluster: banking-kafka
                  strimzi.io/kind: Kafka
                  strimzi.io/name: banking-kafka-kafka
              topologyKey: kubernetes.io/hostname
