apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elasticsearch
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "9"
spec:
  project: default
  source:
    repoURL: https://github.com/ariyendiberil/HomeLab.git
    targetRevision: main
    path: kubernetes/databases/elasticsearch
  destination:
    server: https://kubernetes.default.svc
    namespace: banking-search
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
