apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-loki-datasource
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "13"
spec:
  project: default
  source:
    repoURL: https://github.com/ariyendiberil/HomeLab.git
    targetRevision: main
    path: kubernetes/logging/grafana
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
