apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: default
  source:
    repoURL: https://github.com/ariyendiberil/HomeLab.git
    targetRevision: main
    path: kubernetes/messaging/kafka
  destination:
    server: https://kubernetes.default.svc
    namespace: banking-messaging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
